Repository mikeiken/tam-prog, pull requests merged in 2024-10, with the labels that each got.

#21 Add Basic elements for front building
  frontend/package.json
  frontend/public/plus.png
  frontend/src/App.js
  frontend/src/components/add-item/AddItemButton.js
  frontend/src/components/add-item/add-item-button.css
  frontend/src/components/api/instance.js
  frontend/src/components/card/Card.js
  frontend/src/components/card/modal/Modal.js
  frontend/src/components/card/modal/modal-card-style.css
  frontend/src/components/card/style-card.css
  frontend/src/components/footer/style.css
  frontend/src/components/header/Header.js
  frontend/src/components/header/style.css
  frontend/src/components/main-page/MainPage.js
  frontend/src/components/main-page/style.css
  frontend/yarn.lock
  node_modules/.yarn-integrity
Labels: feature

#23 Add Swagger to Django
  .github/workflows/on-commit-dev.yml
  .github/workflows/on-commit-main.yml
  django-runserver.ps1
  django/requirements.txt
  django/tamprog/tamprog/settings.py
  django/tamprog/tamprog/urls.py
  dotenv-template
Labels: feature

#24 Add environment variable injector scripts for cross-platform support
  django-runserver.ps1
  docker-compose-up.ps1
  docker-compose-up.sh
  docker-dev-up.sh
  env-inject.bat
  env-inject.ps1
  env-inject.sh
Labels: chore

#26 Enhance Docker workflows
  .github/workflows/on-release.yml
  README.md
  dotenv-template
  nginx/Dockerfile
  nginx/nginx.conf
Labels: feature

#28 Update on-release.yml
  .github/workflows/on-release.yml
Labels: bugfix, chore

#29 Update release workflow to trigger on both created and published events
  .github/workflows/on-release.yml
Labels: bugfix

#30 Rename CI workflows for development and main branches
  .github/workflows/on-commit-dev.yml
  .github/workflows/on-commit-main.yml
  .github/workflows/on-release.yml
Labels: chore

#35 Add condition to skip image builds on pull requests in GitHub Actions
  .github/workflows/on-release.yml
Labels: ignore-for-release

#36 Fix static dirs collision
  django/tamprog/tamprog/settings.py
  nginx/nginx.conf
Labels: bugfix

#37 Update static file settings and Nginx configuration for Django
  django/tamprog/tamprog/settings.py
  nginx/nginx.conf
Labels: ignore-for-release

#38 Update GitHub Actions to trigger image builds only on push events
  .github/workflows/on-release.yml
Labels: bugfix

#40 Enhance UI and API integration with routing
  .github/workflows/on-release.yml
  frontend/package.json
  frontend/public/man.jpg
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/add-item/add-item-button.css
  frontend/src/components/api/instance.js
  frontend/src/components/auth/components/auth-style.css
  frontend/src/components/auth/components/background.js
  frontend/src/components/auth/components/form.js
  frontend/src/components/card/Card.js
  frontend/src/components/card/modal/Modal.js
  frontend/src/components/card/modal/modal-card-style.css
  frontend/src/components/card/style-card.css
  frontend/src/components/footer/Footer.js
  frontend/src/components/footer/style.css
  frontend/src/components/header/Header.js
  frontend/src/components/header/style.css
  frontend/src/components/main-page/MainPage.js
  frontend/src/components/main-page/style.css
  frontend/src/index.js
  frontend/yarn.lock
Labels: ignore-for-release

#41 Fix workflow conditions for image builds by restoring event checks
  .github/workflows/on-release.yml
Labels: bugfix

#42 Fix workflow conditions for image builds
  .github/workflows/on-release.yml
Labels: ignore-for-release

#43 Added CORS, pagination and name in fertilizer
  django/requirements.txt
  django/tamprog/garden/migrations/0003_fertilizer_name.py
  django/tamprog/garden/models.py
  django/tamprog/garden/urls.py
  django/tamprog/tamprog/settings.py
  django/tamprog/tamprog/urls.py
Labels: feature

#45 Reverse merge
  django/requirements.txt
  django/tamprog/garden/migrations/0003_fertilizer_name.py
  django/tamprog/garden/models.py
  django/tamprog/garden/urls.py
  django/tamprog/tamprog/settings.py
  django/tamprog/tamprog/urls.py
Labels: ignore-for-release

#44 Improve adaptive design
  frontend/src/App.css
  frontend/src/components/api/instance.js
  frontend/src/components/auth/components/auth-style.css
  frontend/src/components/card/style-card.css
  frontend/src/components/header/Header.js
  frontend/src/components/header/style.css
  frontend/src/components/main-page/MainPage.js
  frontend/src/components/main-page/style.css
Labels: feature

#49 Improved CORS config
  django/requirements.txt
  django/tamprog/garden/admin.py
  django/tamprog/garden/models.py
  django/tamprog/garden/serializers.py
  django/tamprog/garden/urls.py
  django/tamprog/garden/views.py
  django/tamprog/tamprog/settings.py
  django/tamprog/tamprog/urls.py
Labels: feature

#50 Background fix
  frontend/src/App.css
Labels: bugfix

#51 Fix deps
  django/requirements.txt
Labels: bugfix

#53 Dep-fix
  django/requirements.txt
Labels: ignore-for-release

#54 Fix migrations for Docker
  django/Dockerfile
  django/tamprog/tamprog/settings.py
Labels: bugfix

#55 Fix migrations
  django/tamprog/garden/migrations/0004_rename_growth_conditions_plant_description_and_more.py
  django/tamprog/garden/migrations/0005_availableplants_gardenbed_price_and_more.py
  django/tamprog/garden/migrations/0006_rename_garden_id_availableplants_garden_num.py
  django/tamprog/garden/migrations/0007_rename_garden_num_availableplants_garden_id.py
Labels: bugfix

#58 New pages in Web
  frontend/public/students/Анастасия.png
  frontend/public/students/Дарья.png
  frontend/public/students/Денис.png
  frontend/public/students/Леонид.png
  frontend/public/students/Николай.png
  frontend/public/tenor.gif
  frontend/src/App.css
  frontend/src/components/api/instance.js
  frontend/src/components/auth/components/auth-style.css
  frontend/src/components/auth/components/background.js
  frontend/src/components/auth/components/form.js
  frontend/src/components/header/Header.js
  frontend/src/components/main-page/About/about.js
  frontend/src/components/main-page/About/student-card/StudentCard.js
  frontend/src/components/main-page/About/student-card/student.css
  frontend/src/components/main-page/Garden/Garden.js
  frontend/src/components/main-page/Garden/PlotInfo/PlotInfo.js
  frontend/src/components/main-page/Garden/PlotInfo/PlotInfoWindow/PlotInfoWindow.js
  frontend/src/components/main-page/Garden/SearchBlock/SearchBlock.js
  frontend/src/components/main-page/Garden/SearchCard/SearchCard.js
  frontend/src/components/main-page/Garden/garden.css
  frontend/src/components/main-page/MainPage.js
  frontend/src/components/main-page/style.css
Labels: feature

#57 Update CORS
  django/tamprog/garden/models.py
  django/tamprog/garden/urls.py
  django/tamprog/garden/views.py
  django/tamprog/tamprog/settings.py
Labels: feature

#56 New tests
  django/tamprog/garden/tests/conftest.py
  django/tamprog/garden/tests/test_models.py
  django/tamprog/garden/tests/test_serializers.py
  django/tamprog/garden/tests/test_urls.py
  django/tamprog/garden/tests/test_views.py
  django/tamprog/garden/urls.py
Labels: feature

#60 Add conditional execution for build jobs on push events in GitHub Actions
  .github/workflows/on-release.yml
Labels: bugfix

#59 Dev
  .github/workflows/on-release.yml
  .gitignore
  django/Dockerfile
  django/requirements.txt
  django/tamprog/garden/admin.py
  django/tamprog/garden/migrations/0004_rename_growth_conditions_plant_description_and_more.py
  django/tamprog/garden/migrations/0005_availableplants_gardenbed_price_and_more.py
  django/tamprog/garden/migrations/0006_rename_garden_id_availableplants_garden_num.py
  django/tamprog/garden/migrations/0007_rename_garden_num_availableplants_garden_id.py
  django/tamprog/garden/models.py
  django/tamprog/garden/serializers.py
  django/tamprog/garden/tests.py
  django/tamprog/garden/tests/conftest.py
  django/tamprog/garden/tests/test_models.py
  django/tamprog/garden/tests/test_serializers.py
  django/tamprog/garden/tests/test_urls.py
  django/tamprog/garden/tests/test_views.py
  django/tamprog/garden/urls.py
  django/tamprog/garden/views.py
  django/tamprog/pytest.ini
  django/tamprog/tamprog/settings.py
  django/tamprog/tamprog/urls.py
  frontend/package.json
  frontend/public/search.png
  frontend/public/students/Анастасия.png
  frontend/public/students/Дарья.png
  frontend/public/students/Денис.png
  frontend/public/students/Леонид.png
  frontend/public/students/Николай.png
  frontend/public/tenor.gif
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/api/instance.js
  frontend/src/components/auth/components/auth-style.css
  frontend/src/components/auth/components/background.js
  frontend/src/components/auth/components/form.js
  frontend/src/components/card/Card.js
  frontend/src/components/header/Header.js
  frontend/src/components/main-page/About/about.js
  frontend/src/components/main-page/About/student-card/StudentCard.js
  frontend/src/components/main-page/About/student-card/student.css
  frontend/src/components/main-page/Contractor/Contractor.js
  frontend/src/components/main-page/Garden/Garden.js
  frontend/src/components/main-page/Garden/PlotInfo/PlotInfo.js
  frontend/src/components/main-page/Garden/PlotInfo/PlotInfoWindow/PlotInfoWindow.js
  frontend/src/components/main-page/Garden/SearchBlock/SearchBlock.js
  frontend/src/components/main-page/Garden/SearchCard/SearchCard.js
  frontend/src/components/main-page/Garden/garden.css
  frontend/src/components/main-page/License/License.js
  frontend/src/components/main-page/MainPage.js
  frontend/src/components/main-page/style.css
  frontend/src/index.js
  frontend/yarn.lock
Labels: ignore-for-release

#61 Update release workflow
  .github/workflows/on-release.yml
Labels: bugfix

#62 Update release workflow to always set IS_RELEASE to True
  .github/workflows/on-release.yml
Labels: ignore-for-release

#63 Update release workflow to conditionally set IS_RELEASE and add configuration print step
  .github/workflows/on-release.yml
Labels: bugfix

#64 Update release workflow to conditionally set IS_RELEASE and add configuration print step
  .github/workflows/on-release.yml
Labels: ignore-for-release

#65 Update release workflow to set IS_RELEASE based on pull request merge status
  .github/workflows/on-release.yml
Labels: bugfix

#66 Update release workflow to set IS_RELEASE based on pull request merge status
  .github/workflows/on-release.yml
Labels: ignore-for-release

#68 Update release workflow to set IS_RELEASE to True and add tag existence check
  .github/workflows/on-release.yml
Labels: ignore-for-release

#69 Update release workflow and fix API endpoints
  .github/workflows/on-release.yml
  frontend/src/components/api/instance.js
  frontend/src/components/main-page/Garden/SearchBlock/SearchBlock.js
Labels: ignore-for-release

#70 Update API base URL to use localhost
  frontend/src/components/api/instance.js
Labels: bugfix

#71 Added logging for git refs
  .github/workflows/on-release.yml
Labels: feature
