Repository mikeiken/tam-prog, pull requests merged in 2024-11, with the labels that each got.

#77 Added home page, routing
  frontend/public/field1.jpg
  frontend/public/field2.jpg
  frontend/public/user-interface-login.png
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/auth/components/background.js
  frontend/src/components/auth/components/form.js
  frontend/src/components/header/Header.js
  frontend/src/components/main-page/Garden/PlotInfo/PlotInfoWindow/PlotInfoWindow.js
  frontend/src/components/main-page/Garden/SearchCard/SearchCard.js
  frontend/src/components/main-page/Garden/garden.css
  frontend/src/components/main-page/MainPage.js
  frontend/src/components/main-page/style.css
  frontend/src/components/main-page/ui/login-btn/LoginBtn.js
  frontend/src/components/not-found/NotFound.js
Labels: feature

#78 Dotenv-rename
  .env-template
Labels: chore

#79 New docker config
  .github/workflows/on-release.yml
  cleanup.ps1
  cleanup.sh
  django/requirements.txt
  docker-compose-build-up.ps1
  docker-compose-build-up.sh
  docker-compose-build.yml
  docker-compose-dev.yml
  docker-compose-up.ps1
  docker-compose-up.sh
  docker-compose.yml
  frontend/src/components/main-page/MainPage.js
  psql/.dockerignore
  psql/Dockerfile
  psql/build.ps1
  psql/build.sh
Labels: feature

#84 Enhance API with OpenAPI schema and user management improvements
  .gitignore
  django-createsuperuser.ps1
  django/tamprog/fertilizer/views.py
  django/tamprog/garden/views.py
  django/tamprog/orders/views.py
  django/tamprog/plants/views.py
  django/tamprog/tamprog/settings.py
  django/tamprog/tamprog/urls.py
  django/tamprog/user/views.py
  docker-compose-build.yml
  docker-compose.yml
Labels: feature

#85 Enhance API with async calls through Celery & RabbitMQ
  .env-template
  django-runserver.ps1
  django/Dockerfile
  django/entrypoint.ps1
  django/entrypoint.sh
  django/requirements.txt
  django/tamprog/garden/queries.py
  django/tamprog/garden/services.py
  django/tamprog/garden/views.py
  django/tamprog/tamprog/__init__.py
  django/tamprog/tamprog/celery.py
  django/tamprog/tamprog/settings.py
  django/tamprog/user/queries.py
  django/tamprog/user/services.py
  django/tamprog/user/views.py
  docker-compose-build.yml
  env-inject.ps1
Labels: feature

#88 Improve project structure and execution in Docker setup
  django/Dockerfile
  django/entrypoint.sh
  django/requirements.txt
  docker-compose-build.yml
Labels: bugfix

#92 Added autotests
  .github/workflows/on-commit-dev.yml
  .github/workflows/on-commit-main.yml
  django-createsuperuser.ps1
  django-makemigrations.ps1
  django/entrypoint.ps1
  django/entrypoint.sh
  django/tamprog/tamprog/settings.py
  django/tamprog/user/management/commands/__init__.py
  django/tamprog/user/management/commands/auto_createsuperuser.py
  docker-compose-build-up.ps1
  docker-compose-build-up.sh
  docker-compose-build.yml
  docker-compose-up.ps1
  docker-compose-up.sh
  docker-compose.yml
  env-inject.sh
  portainer/Dockerfile
Labels: feature

#91 Added Respone Codes & Token refreshing
  django/tamprog/garden/services.py
  django/tamprog/garden/views.py
  django/tamprog/orders/serializer.py
  django/tamprog/orders/services.py
  django/tamprog/orders/views.py
  django/tamprog/plants/services.py
  django/tamprog/plants/views.py
  django/tamprog/tamprog/settings.py
  django/tamprog/user/models.py
  django/tamprog/user/permission.py
  django/tamprog/user/services.py
  django/tamprog/user/urls.py
  django/tamprog/user/views.py
Labels: feature

#94 Add Django superuser credentials to .env-template
  .env-template
Labels: bugfix

#95 update tests
  django/tamprog/garden/tests.py
  django/tamprog/orders/tests.py
Labels: ignore-for-release

#99 update tests
  django/tamprog/conftest.py
  django/tamprog/plants/tests.py
  django/tamprog/user/tests.py
Labels: ignore-for-release

#100 New logging system
  README.md
  django-createsuperuser.ps1
  django-makemigrations.ps1
  django-manage-py.ps1
  django/requirements.txt
  django/tamprog/fertilizer/services.py
  django/tamprog/fertilizer/views.py
  django/tamprog/garden/permission.py
  django/tamprog/garden/queries.py
  django/tamprog/garden/services.py
  django/tamprog/garden/views.py
  django/tamprog/orders/services.py
  django/tamprog/orders/views.py
  django/tamprog/plants/permissions.py
  django/tamprog/plants/services.py
  django/tamprog/plants/views.py
  django/tamprog/tamprog/settings.py
  django/tamprog/user/management/commands/auto_createsuperuser.py
  django/tamprog/user/models.py
  django/tamprog/user/permission.py
  django/tamprog/user/queries.py
  django/tamprog/user/serializers.py
  django/tamprog/user/services.py
  django/tamprog/user/views.py
Labels: feature

#101 Updated restrictions and logic
  django/tamprog/fertilizer/migrations/0003_fertilizer_price.py
  django/tamprog/fertilizer/models.py
  django/tamprog/garden/migrations/0005_alter_field_price.py
  django/tamprog/garden/migrations/0006_rename_count_beds_field_all_beds_and_more.py
  django/tamprog/garden/models.py
  django/tamprog/garden/serializers.py
  django/tamprog/garden/services.py
  django/tamprog/garden/views.py
  django/tamprog/orders/migrations/0007_alter_order_total_cost.py
  django/tamprog/orders/migrations/0008_rename_action_order_comments.py
  django/tamprog/orders/models.py
  django/tamprog/orders/serializer.py
  django/tamprog/orders/services.py
  django/tamprog/orders/views.py
  django/tamprog/plants/apps.py
  django/tamprog/plants/migrations/0008_bedplant_is_harvested.py
  django/tamprog/plants/migrations/0009_alter_plant_price.py
  django/tamprog/plants/models.py
  django/tamprog/plants/serializers.py
  django/tamprog/plants/services.py
  django/tamprog/plants/signals.py
  django/tamprog/plants/views.py
  django/tamprog/user/migrations/0005_alter_person_wallet_balance_alter_worker_price.py
  django/tamprog/user/models.py
Labels: feature

#102 Added frontend testing
  frontend/package.json
  frontend/src/components/auth/login/components/form.js
  frontend/src/components/auth/register/RegisterForm.js
  frontend/tests/auth.test.js
Labels: chore

#106 Update dorder system
  .github/workflows/on-commit-dev.yml
  .github/workflows/on-commit-main.yml
  django/tamprog/garden/migrations/0007_alter_bed_field.py
  django/tamprog/garden/migrations/0008_field_url.py
  django/tamprog/garden/migrations/0009_alter_field_all_beds_alter_field_count_free_beds.py
  django/tamprog/garden/models.py
  django/tamprog/garden/serializers.py
  django/tamprog/garden/services.py
  django/tamprog/garden/views.py
  django/tamprog/orders/migrations/0009_alter_order_comments.py
  django/tamprog/orders/migrations/0010_remove_order_bed_order_beds_count_order_field.py
  django/tamprog/orders/migrations/0011_order_fertilize.py
  django/tamprog/orders/models.py
  django/tamprog/orders/serializer.py
  django/tamprog/orders/services.py
  django/tamprog/orders/views.py
  django/tamprog/plants/migrations/0010_bedplant_growth_percentage.py
  django/tamprog/plants/migrations/0011_plant_url.py
  django/tamprog/plants/migrations/0012_bedplant_remaining_growth_time_and_more.py
  django/tamprog/plants/migrations/0013_remove_bedplant_remaining_growth_time.py
  django/tamprog/plants/models.py
  django/tamprog/plants/services.py
  django/tamprog/plants/signals.py
  django/tamprog/plants/views.py
  django/tamprog/user/views.py
Labels: feature

#105 Partial design update
  frontend/public/favicon.jpg
  frontend/public/index.html
  frontend/public/plus.svg
  frontend/src/App.js
  frontend/src/components/auth/login/components/auth-style.css
  frontend/src/components/auth/login/components/background.js
  frontend/src/components/auth/login/components/form.js
  frontend/src/components/auth/login/components/welocme/Welcome.js
  frontend/src/components/auth/register/RegisterForm.js
  frontend/src/components/basket-context/BasketContext.js
  frontend/src/components/header/Header.js
  frontend/src/components/main-page/About/about.js
  frontend/src/components/main-page/About/student-card/student.css
  frontend/src/components/main-page/Basket/Basket.js
  frontend/src/components/main-page/Basket/Order/Counter/Counter.js
  frontend/src/components/main-page/Basket/Order/Counter/counter.css
  frontend/src/components/main-page/Basket/Order/Order.js
  frontend/src/components/main-page/Basket/Order/PlantArea/PlantArea.js
  frontend/src/components/main-page/Basket/Order/PlantArea/plant-area.css
  frontend/src/components/main-page/Basket/Order/order.css
  frontend/src/components/main-page/Basket/basket.css
  frontend/src/components/main-page/Contractor/Contractor.js
  frontend/src/components/main-page/Garden/PlotInfo/PlotInfoWindow/PlotInfoWindow.js
  frontend/src/components/main-page/Garden/SearchBlock/SearchBlock.js
  frontend/src/components/main-page/Garden/SearchCard/SearchCard.js
  frontend/src/components/main-page/Garden/garden.css
  frontend/src/components/main-page/License/License.js
  frontend/src/components/main-page/MainPage.js
  frontend/src/components/main-page/style.css
  frontend/src/index.js
Labels: feature
