Repository mikeiken/tam-prog, pull requests merged in 2024-12, with the labels that each got.

#107 Enhance NGINX security and fix related issues
  nginx/nginx.conf
Labels: chore

#108 Refactor NGINX configuration: add build dependencies, enhance security headers, and modularize configuration files
  nginx/Dockerfile
  nginx/default.conf
  nginx/nginx.conf
Labels: chore

#109 New service for order
  django/tamprog/garden/views.py
  django/tamprog/orders/services.py
  django/tamprog/orders/views.py
  django/tamprog/user/views.py
Labels: feature

#111 Enhance authentication, order processing, and logging features
  .env-template
  .github/workflows/on-commit-dev.yml
  .github/workflows/on-commit-main.yml
  django/Dockerfile
  django/requirements.txt
  django/tamprog/tamprog/settings.py
  docker-compose-build.yml
  docker-compose.yml
  frontend/Dockerfile
  frontend/nginx.conf
  nginx/Dockerfile
  nginx/default.conf
Labels: feature

#114 Enhance NGINX security and add Redis support in Django
  .env-template
  .github/workflows/on-commit-dev.yml
  .github/workflows/on-commit-main.yml
  django/Dockerfile
  django/requirements.txt
  django/tamprog/conftest.py
  django/tamprog/garden/tests.py
  django/tamprog/garden/views.py
  django/tamprog/orders/services.py
  django/tamprog/orders/tests.py
  django/tamprog/orders/views.py
  django/tamprog/plants/tests.py
  django/tamprog/tamprog/settings.py
  django/tamprog/user/views.py
  docker-compose-build.yml
  docker-compose.yml
  frontend/Dockerfile
  frontend/nginx.conf
  nginx/Dockerfile
  nginx/default.conf
  nginx/nginx.conf
Labels: ignore-for-release

#113 update test garden
  django/tamprog/garden/tests.py
Labels: ignore-for-release

#116 Styles update
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/auth/login/components/form.js
  frontend/src/components/auth/logout/Logout.js
  frontend/src/components/auth/register/RegisterForm.js
  frontend/src/components/basket-context/BasketContext.js
  frontend/src/components/context/BasketContext.js
  frontend/src/components/context/NotificationContext.jsx
  frontend/src/components/header/Header.js
  frontend/src/components/main-page/About/about.js
  frontend/src/components/main-page/Basket/Basket.js
  frontend/src/components/main-page/Basket/Order/Order.js
  frontend/src/components/main-page/Contractor/Contractor.js
  frontend/src/components/main-page/Contractor/user.css
  frontend/src/components/main-page/Garden/SearchBlock/SearchBlock.js
  frontend/src/components/main-page/Garden/SearchCard/SearchCard.js
  frontend/src/components/main-page/LandingPage/LandingPage.jsx
  frontend/src/components/main-page/LandingPage/main.css
  frontend/src/components/main-page/style.css
  frontend/src/components/main-page/ui/login-btn/LoginBtn.js
  frontend/src/components/main-page/ui/register-btn/RegisterBtn.js
  frontend/src/index.js
Labels: chore

#118 Enhanced database perfomance via new PSQL confuguration
  docker-compose-build.yml
  docker-compose.yml
  nginx/default.conf
Labels: chore

#119 Fixed psql docker late startup
  docker-compose-build.yml
  docker-compose.yml
Labels: bugfix
